# Generated by Django 5.2.2 on 2025-06-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20)),
                ('apellidos', models.TextField(max_length=20)),
                ('numero_Identificacion', models.TextField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_contratacion', models.DateTimeField(auto_now=True)),
                ('numero_telefonico', models.TextField(max_length=15)),
                ('direccion', models.TextField(max_length=20)),
            ],
            options={
                'ordering': ['-fecha_nacimiento'],
            },
        ),
    ]
