# Generated by Django 5.2.2 on 2025-06-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_contratacion',
        ),
    ]
