# Generated by Django 5.2.2 on 2025-06-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_usuarios', '0002_remove_usuario_fecha_contratacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_Identificacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_telefonico',
            field=models.CharField(max_length=15),
        ),
    ]
